api:
    build: .
    ports:
        - 3000:3000
    volumes:
        - .:/app
    links:
        - database
    environment:
        - DB_NAME=legacy-war-api

mongo_data:
    image: mongo:3.0
    volumes:
        - /data/db

database:
    image: mongo:3.0
    ports:
        - "27017:27017"
    volumes_from:
        - mongo_data
    command: --smallfiles
